spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:roguelike
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
        
        